name: Run tests

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: echo "${{ github.HEAD_REF }}"

      - name: 'Checkout parent'
        uses: actions/checkout@v4
        with:
          repository: 'yehudilam/git-submodule-parent'

      - name: 'Checkout submodule'
        uses: actions/checkout@v4
        with:
          repository: 'yehudilam/git-submodule-child'
          path: './git-submodule-child'

      - name: 'Install Dependencies'
        run: yarn install