name: Run tests

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout parent'
        uses: actions/checkout@v4
        with:
          repository: 'yehudilam/git-submodule-parent'
          # submodules: 'recursive'

      - name: 'Create child dir'
        run: mkdir git-submodule-child

      - name: 'Checkout submodule'
        uses: actions/checkout@v4
        with:
          repository: 'yehudilam/git-submodule-child'
          path: './git-submodule-child'

#       - name: 'Checkout repository on branch: ${{ github.REF }}'
# uses: actions/checkout@v4
# with:
#   ref: ${{ github.HEAD_REF }}


      - name: 'Install Dependencies'
        run: yarn install