name: Run tests

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          repository: 'yehudilam/git-submodule-parent'
          submodules: 'recursive'

      - name: 'Install Dependencies'
        run: yarn install