name: Run tests

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        run: echo "${{ github.HEAD_REF }}"

      - name: 'Checkout parent'
        uses: actions/checkout@v4
        with:
          repository: 'yehudilam/git-submodule-parent'
          submodules: true

      # - name: 'Checkout submodule'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: 'yehudilam/git-submodule-child'
      #     path: './git-submodule-child'
      #     ref: ${{ github.HEAD_REF }}

      - name: 'Submodule git fetch'
        run: git submodule foreach --recursive git fetch

      - name: 'Submodule git status'
        run: git submodule foreach --recursive git status

      - name: 'Submodule git branches'
        run: git submodule foreach --recursive git branch

      - name: 'Checkout submodule feature branch'
        run: git submodule foreach --recursive git switch ${{ github.HEAD_REF }}

      - name: 'Install Dependencies'
        run: yarn install

      - name: "Lint"
        run: yarn lint

      - name: "Test"
        run: yarn test
